---

build_python_version: python3
build_work_dir: "{{ ansible_user_dir }}/containers"

# kolla settings
kolla_work_dir: "{{ ansible_user_dir }}/kolla"
# https://review.openstack.org/#/c/624838/
kolla_f28_ref: refs/changes/38/624838/21

kolla_rpm_repos:
  - http://trunk.rdoproject.org/fedora/current/delorean.repo
  - http://trunk.rdoproject.org/fedora/delorean-deps.repo

tripleo_common_work_dir: "{{ ansible_user_dir }}/tripleo-common"
# https://review.openstack.org/#/c/629679/
tripleo_common_f28_ref: refs/changes/79/629679/14

virtenv_work_dir: "{{ ansible_user_dir }}/containers-venv"

container_tag: latest
container_registry: 127.0.0.1:8787
container_namespace: master
container_push: True

python_docker_package_name:
  python2:
    - python-docker
  python3:
    - python3-docker

python_libselinux_package_name:
  python2:
    - python-libselinux
  python3:
    - python3-libselinux

python_pip_package_name:
  python2:
    - python-pip
  python3:
    - python3-pip

python_venv_package_name:
  python2:
    - python-virtualenv
  python3:
    - python3-virtualenv

python_venv_command:
  python2: virtualenv
  python3: virtualenv-3

tripleoclient_package_name:
  python2:
    - python-tripleoclient
  python3:
    - python3-tripleoclient
